"""Ground-truth tests: TECHNIQUE_CATALOG must match the official MITRE ATT&CK for ICS matrix.

WHY THIS TEST EXISTS
--------------------
An earlier revision of the technique catalog in ``ics_scanner/mitre_attack.py``
had drifted from the real matrix: IDs were shifted (e.g. "Modify Program"
listed as T0848/T0879/T0887/T0894 when MITRE never duplicates a name and the
real ID is T0889), and one referenced ID (T0808) did not exist at all. Every
value in that file LOOKED plausible — that is exactly why it must be
validated against an authoritative source instead of relying on recall.

The ground truth is ``tests/fixtures/attack_ics_official.json``, generated
verbatim from MITRE's official STIX bundle by
``scripts/build_attack_fixture.py`` (never hand-edited). To refresh it when
ATT&CK for ICS is updated:

    # download the official bundle, then:
    python scripts/build_attack_fixture.py ics-attack.json

Any mismatch between the catalog and the fixture fails HERE, at commit/CI
time, instead of in front of a SOC analyst or an interviewer.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from ics_scanner.mitre_attack import PROTOCOL_FUNCTION_MAPPING, TECHNIQUE_CATALOG

FIXTURE = Path(__file__).parent / "fixtures" / "attack_ics_official.json"


def _load_official() -> dict[str, dict]:
    data = json.loads(FIXTURE.read_text(encoding="utf-8"))
    assert "generated by scripts/build_attack_fixture.py" in data["_meta"]["note"].lower(), (
        "Fixture metadata invalid — regenerate with scripts/build_attack_fixture.py"
    )
    return data["techniques"]


OFFICIAL = _load_official()


def _norm_tactic(tactic: str) -> frozenset[str]:
    """Normalize a tactic string to a comparable set.

    Accepts both repo style ('Execution, Persistence') and STIX style
    ('command-and-control') so only real disagreements fail, not formatting.
    """
    return frozenset(
        part.strip().lower().replace("-", " ") for part in tactic.split(",") if part.strip()
    )


# ---------------------------------------------------------------------------
# 1. Structural invariants (no ground truth needed — MITRE rules)
# ---------------------------------------------------------------------------


def test_no_duplicate_technique_names():
    """MITRE ATT&CK never assigns the same name to two technique IDs."""
    names = [t.name.strip() for t in TECHNIQUE_CATALOG.values()]
    duplicates = {n for n in names if names.count(n) > 1}
    assert not duplicates, (
        f"Duplicate technique names (impossible in real ATT&CK — usually a sign "
        f"of fabricated IDs): {sorted(duplicates)}"
    )


def test_catalog_ids_are_well_formed():
    for tid in TECHNIQUE_CATALOG:
        assert tid.startswith("T08"), f"{tid} is not a T08xx ATT&CK for ICS technique ID"
        assert tid[1:].isdigit(), f"{tid} is malformed"
        assert len(tid) == 5, f"{tid} is malformed"


def test_mapping_references_resolve_in_catalog():
    """Every technique ID used by PROTOCOL_FUNCTION_MAPPING must exist in the catalog."""
    referenced = {
        tid
        for proto in PROTOCOL_FUNCTION_MAPPING.values()
        for tids in proto.values()
        for tid in tids
    }
    missing = sorted(referenced - set(TECHNIQUE_CATALOG))
    assert not missing, f"PROTOCOL_FUNCTION_MAPPING references unknown catalog IDs: {missing}"


# ---------------------------------------------------------------------------
# 2. Ground truth: catalog vs official MITRE STIX fixture
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(("tid", "technique"), sorted(TECHNIQUE_CATALOG.items()))
def test_technique_exists_in_official_attack(tid, technique):
    """Every catalog ID must exist in the official ATT&CK for ICS matrix."""
    assert tid in OFFICIAL, (
        f"{tid} ('{technique.name}') does not exist in official MITRE ATT&CK for ICS. "
        f"If the technique is real, find its correct ID at "
        f"https://attack.mitre.org/techniques/ics/ — do not invent IDs."
    )


@pytest.mark.parametrize(("tid", "technique"), sorted(TECHNIQUE_CATALOG.items()))
def test_technique_name_matches_official(tid, technique):
    """Catalog name must match the official STIX name exactly (case-sensitive)."""
    official = OFFICIAL.get(tid)
    if official is None:
        pytest.skip("nonexistent ID — covered by test_technique_exists_in_official_attack")
    assert technique.name == official["name"], (
        f"{tid}: catalog says '{technique.name}' but official ATT&CK name is "
        f"'{official['name']}'. Catalog URL: {technique.url}"
    )


@pytest.mark.parametrize(("tid", "technique"), sorted(TECHNIQUE_CATALOG.items()))
def test_technique_tactics_match_official(tid, technique):
    """Catalog tactics must be exactly the official kill-chain phases for that ID."""
    official = OFFICIAL.get(tid)
    if official is None:
        pytest.skip("nonexistent ID — covered by test_technique_exists_in_official_attack")
    assert _norm_tactic(technique.tactic) == _norm_tactic(",".join(official["tactics"])), (
        f"{tid} ('{official['name']}'): catalog tactics "
        f"'{technique.tactic}' != official {official['tactics']}"
    )


@pytest.mark.parametrize(("tid", "technique"), sorted(TECHNIQUE_CATALOG.items()))
def test_technique_not_deprecated_or_revoked(tid, technique):
    """Do not map to techniques MITRE has revoked/deprecated."""
    official = OFFICIAL.get(tid)
    if official is None:
        pytest.skip("nonexistent ID — covered by test_technique_exists_in_official_attack")
    assert not official.get("deprecated", False), (
        f"{tid} ('{technique.name}') is revoked/deprecated in official ATT&CK"
    )


def test_catalog_url_format_matches_id():
    for tid, technique in TECHNIQUE_CATALOG.items():
        assert technique.url == f"https://attack.mitre.org/techniques/{tid}/", (
            f"{tid}: URL {technique.url} does not match its own ID"
        )


# ---------------------------------------------------------------------------
# 3. Optional live check against MITRE (opt-in, never breaks offline CI)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not os.environ.get("RUN_NETWORK_TESTS"),
    reason="set RUN_NETWORK_TESTS=1 to verify fixture freshness online",
)
def test_fixture_matches_live_mitre_matrix():
    """Fail if the committed fixture is stale vs MITRE's live ICS matrix."""
    import urllib.request

    with urllib.request.urlopen(
        "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/ics-attack/ics-attack.json",
        timeout=30,
    ) as resp:
        live = json.load(resp)
    live_ids = {
        ref["external_id"]
        for obj in live["objects"]
        if obj.get("type") == "attack-pattern"
        for ref in obj.get("external_references", [])
        if ref.get("source_name") == "mitre-attack"
    }
    stale = sorted(set(OFFICIAL) - live_ids)
    assert not stale, f"Fixture contains IDs no longer in the live matrix: {stale}"
