#!/usr/bin/env python3
"""Regenerates tests/fixtures/attack_ics_official.json from the official MITRE STIX bundle.

Anti-hallucination ground truth: the fixture is NOT hand-written. It is
extracted verbatim from MITRE's official STIX/JSON bundle so that the
TECHNIQUE_CATALOG in ics_scanner/mitre_attack.py can never silently drift
from the real ATT&CK for ICS matrix.

Usage:
    python scripts/build_attack_fixture.py [path/to/ics-attack.json]

Default input: the official bundle downloaded from
https://github.com/mitre-attack/attack-stix-data (attack-ics bundle).
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

DEFAULT_INPUT = "ics-attack.json"
FIXTURE_PATH = (
    Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "attack_ics_official.json"
)
SOURCE_URL = "https://github.com/mitre-attack/attack-stix-data (attack-ics)"


def build_fixture(stix_path: str) -> dict:
    bundle = json.loads(Path(stix_path).read_text(encoding="utf-8"))
    techniques: dict[str, dict] = {}
    for obj in bundle.get("objects", []):
        if obj.get("type") != "attack-pattern":
            continue
        tid = next(
            (
                ref["external_id"]
                for ref in obj.get("external_references", [])
                if ref.get("source_name") == "mitre-attack"
            ),
            None,
        )
        if not tid:
            continue
        tactics = sorted(
            phase["phase_name"]
            for phase in obj.get("kill_chain_phases", [])
            if phase.get("kill_chain_name") == "mitre-ics-attack"
        )
        techniques[tid] = {
            "name": obj["name"],
            "tactics": tactics,
            "url": f"https://attack.mitre.org/techniques/{tid}/",
            "deprecated": obj.get("x_mitre_deprecated", False) or obj.get("revoked", False),
        }
    return {
        "_meta": {
            "source": SOURCE_URL,
            "stix_spec_version": bundle.get("spec_version", "?"),
            "technique_count": len(techniques),
            "generated": date.today().isoformat(),
            "note": "Generated by scripts/build_attack_fixture.py. Do NOT hand-edit.",
        },
        "techniques": techniques,
    }


def main() -> int:
    stix_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_INPUT
    fixture = build_fixture(stix_path)
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(json.dumps(fixture, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH} ({fixture['_meta']['technique_count']} techniques)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
